version: "3.7"

services:
    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: truck_management
        ports:
            - 3306:3306
        volumes: 
            - ./docker/database/:/docker-entrypoint-initdb.d

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080