version: "3.7"

services:
    app:
        image: golang:1.16.5-alpine3.14
        working_dir: /app
        volumes: 
            - ./:/app
        command: 'go run main.go'
        depends_on: 
            - db
        restart: on-failure
        ports: 
            - 3000:3000

    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: truck_management
        ports:
            - 3306:3306
        volumes: 
            - ./docker/database/:/docker-entrypoint-initdb.d