name: CI

on: [push]

jobs:
  CI:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"

      - name: Running Unit Tests
        run: go test ./truck-management/...
